### ISSUE TITLE
Could not find method google() for arguments [] on repository container

### ISSUE THREAD

**Issue by csyang6052** [rosjava/rosjava_bootstrap#78]
I tried to build a rosjava package using the "catkin_create_rosjava_pkg" command. 

FAILURE: Build failed with an exception.
* Where:
Script 'https://github.com/rosjava/rosjava_bootstrap/raw/kinetic/buildscript.gradle' line: 44
* What went wrong:
A problem occurred evaluating script.
> Could not find method google() for arguments [] on repository container.

My setup :
ROS - kinetic
android-studio - 3.2.1
gradle - 4.6
Android/Sdk/build-tools - 25.02, 26.02, 28.03

**Comment by jubeira** [comment]
Hi @csyang6052, thanks for the report.
This is because of the changes introduced in https://github.com/rosjava/rosjava_bootstrap/pull/73. I just tested the command and I didn't have this problem. Did you install `rosjava_build_tools` from source or from debians? You will need to update them for this to work properly. I still haven't released `rosjava_build_tools` as a debian package, so you will need to build from source for now (see [this tutorial](http://wiki.ros.org/rosjava/Tutorials/kinetic/Source%20Installation))

**Comment by csyang6052** [comment]
Hi @jubeira , many thanks, it works for me now.
